spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./cafelatte
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9000